package parser

// ConstructionInlineExpectation is an ephemeral parser-independent proof fact
// for one semantic inline node generated by typed construction. Parent is -1
// for a paragraph child or the index of another expectation for direct nesting.
type ConstructionInlineExpectation struct {
	Kind            Kind
	SyntaxRange     Range
	ContentRange    Range
	Marker          byte
	DelimiterLength int
	Parent          int
}
